### ISSUE TITLE
怎么老显示try to get ip list page

### ISSUE THREAD

**Issue by yingnengdd** [dhgdhg/OutLook-Email-Register#2]
怎么老显示try to get ip list page:https:/ip.ihuan.me/today................................................

**Comment by 7-Leaf** [comment]
他在从这个网址https://ip.ihuan.me/today获取代理ip, 然后尝试使用代理

**Comment by yingnengdd** [comment]
但是一直显示try ,一直要等吗？

**Comment by yingnengdd** [comment]
![image](https://user-images.githubusercontent.com/93358108/141216815-29141028-8b21-4655-aff5-49f1d3c28130.png)

**Comment by yingnengdd** [comment]
是上面的网址没错，

**Comment by 7-Leaf** [comment]
可以临时去掉代理试下
```
def create_driver():
    port = utils.free_port()
    options = ChromeOptions()
    desired_capabilities = DesiredCapabilities().CHROME
    desired_capabilities['pageLoadStrategy'] = 'none'
    os.popen(
        'chrome.exe --remote-debugging-port={} --user-data-dir={}'.format(
            port, tempfile.mkdtemp())
    )
    options.add_experimental_option(
        'debuggerAddress', '127.0.0.1:{}'.format(port))
    driver = Chrome(
        options=options, desired_capabilities=desired_capabilities)
    driver.set_window_position(0, 0)
    driver.set_window_size(700, 600)
    return driver

if __name__ == '__main__':
    driver = create_driver()
    register_success = start_register(driver)
```

**Comment by akiha0** [comment]
你好，我想问下怎么用的

**Comment by 7-Leaf** [comment]
> 你好，我想问下怎么用的

配置一下python和selenium环境然后执行spider.py

**Comment by akiha0** [comment]
> > 你好，我想问下怎么用的
> 
> 配置一下python和selenium环境然后执行spider.py
执行了，但是一直在获取代理地址
还有不知道怎么将账户密码写在哪个文件，还是在代码里面更改？

**Comment by 7-Leaf** [comment]
> > > 你好，我想问下怎么用的
> > 
> > 
> > 配置一下python和selenium环境然后执行spider.py
> > 执行了，但是一直在获取代理地址
> > 还有不知道怎么将账户密码写在哪个文件，还是在代码里面更改？

可以关闭代理试下
密码写入pass.txt文件, 会自己创建, 对 可以在代码里面改

**Comment by akiha0** [comment]
![image](https://user-images.githubusercontent.com/49738041/141957305-8497bc57-b64e-4af1-8be7-1484405fecff.png)
它是这样显示的，都到负数了。

**Comment by 7-Leaf** [comment]
> ![image](https://user-images.githubusercontent.com/49738041/141957305-8497bc57-b64e-4af1-8be7-1484405fecff.png) 它是这样显示的，都到负数了。

可以关闭代理试下

https://github.com/twfb/OutLook-Email-Register/issues/2#issuecomment-965895209

**Comment by akiha0** [comment]
> 可以临时去掉代理试下
> 
> ```
> def create_driver():
>     port = utils.free_port()
>     options = ChromeOptions()
>     desired_capabilities = DesiredCapabilities().CHROME
>     desired_capabilities['pageLoadStrategy'] = 'none'
>     os.popen(
>         'chrome.exe --remote-debugging-port={} --user-data-dir={}'.format(
>             port, tempfile.mkdtemp())
>     )
>     options.add_experimental_option(
>         'debuggerAddress', '127.0.0.1:{}'.format(port))
>     driver = Chrome(
>         options=options, desired_capabilities=desired_capabilities)
>     driver.set_window_position(0, 0)
>     driver.set_window_size(700, 600)
>     return driver
> 
> if __name__ == '__main__':
>     driver = create_driver()
>     register_success = start_register(driver)
> ```

是这个关闭代理么？怎么使用呢？
是将def get_ip_list():整个替换掉么？

**Comment by 7-Leaf** [comment]
> > 可以临时去掉代理试下
> > ```
> > def create_driver():
> >     port = utils.free_port()
> >     options = ChromeOptions()
> >     desired_capabilities = DesiredCapabilities().CHROME
> >     desired_capabilities['pageLoadStrategy'] = 'none'
> >     os.popen(
> >         'chrome.exe --remote-debugging-port={} --user-data-dir={}'.format(
> >             port, tempfile.mkdtemp())
> >     )
> >     options.add_experimental_option(
> >         'debuggerAddress', '127.0.0.1:{}'.format(port))
> >     driver = Chrome(
> >         options=options, desired_capabilities=desired_capabilities)
> >     driver.set_window_position(0, 0)
> >     driver.set_window_size(700, 600)
> >     return driver
> > 
> > if __name__ == '__main__':
> >     driver = create_driver()
> >     register_success = start_register(driver)
> > ```
> 
> 是这个关闭代理么？怎么使用呢？ 是将def get_ip_list():整个替换掉么？

替换函数

**Comment by akiha0** [comment]
替换掉get_ip_list了  还是用不了

`'chrome.exe' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "C:\Users\10292\Desktop\spider.py", line 227, in <module>
    driver = create_driver()
  File "C:\Users\10292\Desktop\spider.py", line 220, in create_driver
    driver = Chrome(
  File "C:\Users\10292\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\10292\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\10292\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 266, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\10292\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 357, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\10292\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\10292\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:54697
from chrome not reachable
Stacktrace:
Backtrace:
	Ordinal0 [0x009E6023+2514979]
	Ordinal0 [0x0097F6B1+2094769]
	Ordinal0 [0x00882590+1058192]
	Ordinal0 [0x0087742E+1012782]
	Ordinal0 [0x008A03DE+1180638]
	Ordinal0 [0x0089A26B+1155691]
	Ordinal0 [0x0089A051+1155153]
	Ordinal0 [0x008CA8EF+1353967]
	Ordinal0 [0x008CA55A+1353050]
	Ordinal0 [0x008C61EB+1335787]
	Ordinal0 [0x008A2617+1189399]
	Ordinal0 [0x008A3479+1193081]
	GetHandleVerifier [0x00B75624+1579748]
	GetHandleVerifier [0x00C20417+2279639]
	GetHandleVerifier [0x00A7473B+527355]
	GetHandleVerifier [0x00A737E9+523433]
	Ordinal0 [0x00984BF9+2116601]
	Ordinal0 [0x00989238+2134584]
	Ordinal0 [0x00989372+2134898]
	Ordinal0 [0x00992EB1+2174641]
	BaseThreadInitThunk [0x75EA6739+25]
	RtlGetFullPathName_UEx [0x774D8AFF+1215]
	RtlGetFullPathName_UEx [0x774D8ACD+1165]


进程已结束，退出代码为 1
`

**Comment by 7-Leaf** [comment]
> 替换掉get_ip_list了 还是用不了
> 
> `'chrome.exe' �����ڲ����ⲿ���Ҳ���ǿ����еĳ��� ���������ļ��� Traceback (most recent call last): File "C:\Users\10292\Desktop\spider.py", line 227, in driver = create_driver() File "C:\Users\10292\Desktop\spider.py", line 220, in create_driver driver = Chrome( File "C:\Users\10292\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in **init** super(WebDriver, self).**init**(DesiredCapabilities.CHROME['browserName'], "goog", File "C:\Users\10292\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in **init** RemoteWebDriver.**init**( File "C:\Users\10292\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 266, in **init** self.start_session(capabilities, browser_profile) File "C:\Users\10292\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 357, in start_session response = self.execute(Command.NEW_SESSION, parameters) File "C:\Users\10292\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute self.error_handler.check_response(response) File "C:\Users\10292\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:54697 from chrome not reachable Stacktrace: Backtrace: Ordinal0 [0x009E6023+2514979] Ordinal0 [0x0097F6B1+2094769] Ordinal0 [0x00882590+1058192] Ordinal0 [0x0087742E+1012782] Ordinal0 [0x008A03DE+1180638] Ordinal0 [0x0089A26B+1155691] Ordinal0 [0x0089A051+1155153] Ordinal0 [0x008CA8EF+1353967] Ordinal0 [0x008CA55A+1353050] Ordinal0 [0x008C61EB+1335787] Ordinal0 [0x008A2617+1189399] Ordinal0 [0x008A3479+1193081] GetHandleVerifier [0x00B75624+1579748] GetHandleVerifier [0x00C20417+2279639] GetHandleVerifier [0x00A7473B+527355] GetHandleVerifier [0x00A737E9+523433] Ordinal0 [0x00984BF9+2116601] Ordinal0 [0x00989238+2134584] Ordinal0 [0x00989372+2134898] Ordinal0 [0x00992EB1+2174641] BaseThreadInitThunk [0x75EA6739+25] RtlGetFullPathName_UEx [0x774D8AFF+1215] RtlGetFullPathName_UEx [0x774D8ACD+1165]
> 
> 进程已结束，退出代码为 1 `

有没有先配置selenium环境, chrome driver, 还有把chrome放到path

**Comment by akiha0** [comment]
![image](https://user-images.githubusercontent.com/49738041/142093034-a10089d8-2c30-4a83-a805-7968a5dc42ec.png)
替换get_ip_list的这段报错了
